version: "3.9"

services:
  app:
    image: vakho/java-app
    depends_on:
      - db
    networks:
      - backend
  db: # ბაზას არ ვიყენებთ :( უბრალოდ მიწერია (ვითომ ვიყენებთ)
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    networks:
      - backend

networks:
  backend: